config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :arts do
    resources :reviews
  end
  resources :users
  resources :reviews


  get "dashboard",            to: 'pages#dashboard'
  get "paintings",            to: 'pages#paintings'
  get "drawings",             to: 'pages#drawings'
  get "digital_paintings",    to: 'pages#digital_paintings'
  get "photography",          to: 'pages#photography'

  get "my_paintings",         to: 'pages#my_paintings'
  get "my_drawings",          to: 'pages#my_drawings'
  get "my_digits",            to: 'pages#my_digits'
  get "my_photos",            to: 'pages#my_photos'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  has_one_attached :photo, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user

  CATEGORIES = ['painting', 'drawing', 'digital painting', 'photography']
  validates_inclusion_of :category, :in => CATEGORIES

  validates :photo, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :art

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :photo
  belongs_to :user

  CATEGORIES = ['painting', 'drawing', 'digital painting', 'photography']
  validates_inclusion_of :category, :in => CATEGORIES
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :art
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :arts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  def index
    @user = current_user
    @arts = Art.where(user_id: current_user.id)
  end

  def show
    @art = Art.find(params[:id])
    @reviews = @art.reviews
  end

  def new
    @user = current_user
    @art = Art.new
  end

  def create
    @user = current_user
    @art = Art.new(art_params)
    @art.user_id = current_user.id

    if @art.save
      flash[:notice] = "Post created"
      redirect_to arts_path
    else
      flash[:notice] = "Something went wrong, please check the form again"
    end
  end

  def edit
    @art = Art.find(params[:id])
    @user = current_user
  end

  def update
    @art = Art.find(params[:id])
    @user = current_user

    if @art.update(art_params_update)
      flash[:notice] = "post updated"
      redirect_to arts_path
    else
      render :edit
    end

  end

  def destroy
    @art = Art.find(params[:id])
    @user = current_user
    if @art.destroy
      flash[:notice] = "Post deleted"
      redirect_to arts_path
    end
  end



  private

  def art_params
    params.require(:art).permit(:title, :description, :user_id, :photo, :category)
  end

  def art_params_update
    params.require(:art).permit(:title, :description, :photo, :user_id, :category)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @user = current_user
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @user = current_user
    @art = Art.find(params[:art_id])
    @comment = Comment.new
  end

  def create
    @user = current_user
    @comment = Comment.new(comment_params)
    @comment.art = @art

    if @comment.save
      flash[:notice] = "comment posted"
      redirect_to dashboard_path
    else
      flash[:notice] = "Something went wrong"
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @user = current_user
  end

  def update
    @comment = Comment.find(params[:id])
    @user = current_user

    if @comment.update(comment_params_update)
      flash[:notice] = "comment updated"
      redirect_to dashboard
    else
      render :edit
    end

  end

  def destroy
    @comment = Comment.find(params[:id])
    @user = current_user
    if @comment.destroy
      flash[:notice] = "comment deleted"
      redirect_to dashboard
    end
  end



  private

  def comment_params
    params.require(:comment).permit(:content, :art_id, :user_id)
  end

  def comment_params_update
    params.require(:comment).permit(:content, :art_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    @user = current_user
    @reviews = Review.all
  end

  def my_paintings
    @user = current_user
    @arts = Art.where(user_id: current_user.id)
  end

  def my_drawings
    @user = current_user
    @arts = Art.where(user_id: current_user.id)
  end

  def my_digits
    @user = current_user
    @arts = Art.where(user_id: current_user.id)
  end

  def my_photos
    @user = current_user
    @arts = Art.where(user_id: current_user.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @user = current_user
    # @review.art = @user.art
    @reviews = Review.where(art_id: @user.arts.ids)
    @mines = Review.where(user_id: @user.id)
  end

  def show
    @user = current_user
    @review = Review.find(params[:id])
  end

  def new
    @user = current_user
    @art = Art.find(params[:art_id])
    @review = current_user.reviews.new
  end

  def create
    @user = current_user
    @review = current_user.reviews.new(review_params)
    @art = Art.find(params[:art_id])
    @review.art_id = @art.id

    if @review.save
      flash[:notice] = "comment posted"
      redirect_to art_path(@art)
    else
      flash[:notice] = "Something went wrong"
    end
  end

  def edit
    @review = Review.find(params[:id])
    @user = current_user
  end

  def update
    @user = current_user
    @review = Review.find(params[:id])
      if @review.update(review_params_update)
        flash[:notice] = "post updated"
        redirect_to art_path(@review.art)
      else
        render :edit
      end

  end

  def destroy
    @user = current_user
    @review = Review.find(params[:id])
    @art = @review.post
    @art.user_id = current_user.id

    if @review.destroy
      flash[:notice] = "Post deleted"
      redirect_to art_path(@review.art)
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :art_id, :user_id)
  end

  def review_params_update
    params.require(:review).permit(:content, :art_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params_update)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname,:city,:email,:photo, :password)
  end

  def user_params_update
    params.require(:user).permit(:nickname,:city,:email,:photo, :password)

    # this is a test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/arts/edit.html.erb
<div class="art-form">
  <div class="Form">
    <h1>Arty Space</h1>
    <p>Edit your post</p>
    <%= simple_form_for @art do |f| %>
      <div class="formbody">
        <%= f.input :title %>
        <%= f.input :description %>
        <small>Category :</small>
        <%= f.select :category, Art::CATEGORIES %>
        <br><br>
        <%= f.input :photo, as: :file %>
        <% f.input :current_user_id, input_html: {value: params[:current_user_id]} %>
        <br><br>
      </div>
      <div class="sub">
        <%= f.button :submit, 'Post' %>
      </div>
    <% end %>
  </div>


</div>

app/views/arts/index.html.erb
<div class="giant">
  <div class="container">
    <div class="bbbox">

      <div class="big-card">
        <h1 class="mygallery-title">My Gallery</h1>
          <br>
          <div class="creategall">
            <div class="creatext">
              <h2>Fill your galleries</h2>
              <p>Upload your artwork and make it visible in one click !</p>
              <br>
              <%= link_to "New post", new_art_path %>
              <br><br>
              <hr>
            </div>
          </div>

        <%# ----------------------------------------------------------------------------------- %>
        <div class="big">
          <div class="mygallery-box gall">
            <div class="mypaint boxxx">
              <h3>My paintings
              <span>
                <%= link_to my_paintings_path, class:"minilink" do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %>
              </span>
              </h3>
              <div class="myart">
                <% paint = @arts.where(category: "painting")%>
                <% paint.first(4).each do |art| %>
                  <div class="art">
                    <% if art.user == current_user %>
                      <%= link_to art_path(art) do %>
                        <%= cl_image_tag art.photo.key, width:'180px', height: '130px' %>
                      <% end %>
                    <% end %>

                  </div>
                <% end %>
              </div>

            </div>

            <div class="mydraw boxxx">
              <br><br>
              <h3>My drawings
              <span>
                <%= link_to my_drawings_path, class:"minilink" do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %>
              </span>
              </h3>
              <div class="myart">
                <% draw = @arts.where(category: "drawing")%>
                <% draw.first(4).each do |art| %>
                  <div class="art">
                    <% if art.user == current_user %>
                      <%= link_to art_path(art) do %>
                        <%= cl_image_tag art.photo.key, width:'180px', height: '130px' %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>

              </div>

            </div>

            <div class="mydigit boxxx">
              <br><br>
              <h3>My digital paintings
              <span>
                <%= link_to my_digits_path, class:"minilink" do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %>
              </span>
              </h3>
              <div class="myart">
                <% digit= @arts.where(category: "digital painting") %>
                <% digit.first(4).each do |art| %>
                  <div class="art">
                    <% if art.user == current_user %>
                      <%= link_to art_path(art) do %>
                        <%= cl_image_tag art.photo.key, width:'180px', height: '130px' %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>

            </div>

            <div class="myphoto boxxx">
              <br><br>
              <h3>My photographs
              <span>
                <%= link_to my_photos_path, class:"minilink" do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %>
              </span>
              </h3>
              <div class="myart">
                <% photo = @arts.where(category: "photography")%>
                <% photo.first(4).each do |art| %>
                  <div class="art">
                    <% if art.user == current_user %>
                      <%= link_to art_path(art) do %>
                        <%= cl_image_tag art.photo.key, width:'180px', height: '130px' %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>

            </div>
          </div>

        </div>
      </div>

        <div class="rightside">
          <div class="right">
            <div class="profile-box">
              <div class="user-infos">
                <h3 class="user">Welcome <br><%= @user.nickname %> !</h3>
                <br><br>
                <p><%= current_user.email %></p>
                <p class ="city"><%= @user.city %></p>
              </div>
              <div class="user-photo">
                <% if @user.photo.attached? %>
                  <%= cl_image_tag @user.photo.key , width:'100px',class:'av' %>
                <% else %>
                  <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1671992140/click%20n%20pole/avatar_p2fgt6.jpg', width:'100px',class:'av' %>
                <% end %>
                <br>
              </div>
              <div class="link-user-edit">
                <%= link_to"Edit", edit_user_path(@user) %>
              </div>
              <hr>
            </div>
            <div class="mess-box">
              <h3>Reviews</h3>
              <br><br>
              <p>My 3 last reviews:</p>
              <p><small>review 1</small></p>
              <p><small>review 2</small></p>
              <p><small>review 3</small></p>
              <%= link_to"Reviews","#" %>
            </div>
          </div>
        </div>


      </div>
  </div>
</div>

app/views/arts/new.html.erb
<div class="art-form">
  <div class="Form">
    <h1>Arty Space</h1>
    <p>Share your art !</p>
    <%= simple_form_for @art do |f| %>
      <div class="formbody">
        <%= f.input :title %>
        <%= f.input :description %>
        <small>Category :</small>
        <%= f.select :category, Art::CATEGORIES %>
        <br><br>
        <%= f.input :photo, as: :file %>
        <% f.input :current_user_id, input_html: {value: params[:current_user_id]} %>
        <br><br>
      </div>
      <div class="sub">
        <%= f.button :submit, 'Post' %>
      </div>
    <% end %>
  </div>
</div>

app/views/arts/show.html.erb
<div class="container">
  <div class="motherbox">
    <br>
      <div class="navlinkup">
        <%= link_to "My galleries", arts_path %>
        <% if @art.category == "painting" %>
          <%= link_to "Back", paintings_path %>
        <% elsif @art.category == "drawing" %>
          <%= link_to "Back", drawings_path %>
           <% elsif @art.category == "digital painting" %>
          <%= link_to "Back", digital_paintings_path %>
           <% elsif @art.category == "photography" %>
          <%= link_to "Back", photography_path %>
        <% end %>
        <br><br>
      </div>

      <div class="box-show">
        <h1><%= @art.title %></h1>
          <p><%= @art.description %></p>
          <p><small style= "font-size:10px;">posted on <%= @art.created_at.strftime("%d/%m/%Y") %> </small></p>
          <div class="fullimg">
            <%= cl_image_tag @art.photo.key, class:"fullsize"%>
          </div>
          <br>
      </div>
      <div class="current links">
        <%if @art.user == current_user %>
            <%= link_to "edit | ", edit_art_path(@art), class:"miniedit" %>
            <%= link_to "delete", art_path(@art), method: :delete, data:{confirm: "Are you sur you want to delete this post ?"} , class:'minidel'%>
          <% end %>
          <br><br>
      </div>

      <div class="shadow">
        <div class="comments-box">
          <div class="title-comment">
            <h6>This artwork has <span class="count"><b><%= @art.reviews.count %></b></span> comment(s) </h6>
            <p><%= link_to"Comment", new_art_review_path(@art), class:"comm" %></p>
          </div>

          <br>
          <% @art.reviews.each do |review| %>
            <div class="commentdiv">

                <p>
                  <% if review.user.photo.attached? %>
                    <%= cl_image_tag review.user.photo.key, class:"avatar" %>
                  <% else %>
                    <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1671992140/click%20n%20pole/avatar_p2fgt6.jpg', class:"avatar" %>
                  <% end %>
                  <small><em><%= review.user.email %> |</em></small>  <small style= "font-size:9px;"> <em><%= review.created_at.strftime("%d/%m/%Y") %></em> </small>
                </p>
                <p><%= review.content %></p>
                <% if review.user == current_user %>
                  <small><%= link_to "edit", edit_art_review_path(@art), class:"miniedit" %> </small>|
                  <small><%= link_to "delete", art_review_path(@art), method: :delete, dat: {confirm: "Are you sur you want to delete this comment ?"}, class:"minidel" %></small>
                <% end %>
                <hr>
            </div>
          <% end %>
          <%= link_to "Top of the page", art_path(@art), class: 'top' %>

        </div>
      </div>
  </div>



</div>

app/views/comments/new.html.erb
<div class="new-comment-form">
  <%#= simple_form_for [@art,@comment] do |f| %>
      <%#= f.input :content %>
      <%# f.input :user_id, input_html: {value: params[:current_user_id]} %>
      <%# f.input :art_id, input_html: {value: params[:art_id]} %>
      <br><br>
      <%#= f.button :submit, 'Post' %>
    <%# end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artyspace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8110e6fe91.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;700&family=Poppins:wght@100;200;500&family=Work+Sans:wght@300;400;600;800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar'  %>
    <%= render 'shared/flashes' %>
    <%# unless params[:action] == 'home' %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="padbox">
  <div class="dash-box">

      <div class="left">
        <div class="uptext">
          <h1>Welcome to <span class ="yellow">Arty Space</span></h1>
          <h2>Your digital gallery !</h2>
        </div>
        <div class="sharebox">
          <h3>Post my work</h3>
          <p> Share your art all around the world and increase your visibility !</p>
          <p>Create your own galleries</p>
          <%= link_to "Post", arts_path %>
        </div>

        <div class="viewbox">
          <h2>Galleries</h2>
          <p>Take a look at our artists work. Thousand pieces of art in our galleries!</p>
          <div class="galleries-mini">
            <div class="card">
              <p>Painting</p>
              <%=  link_to paintings_path do %>
                <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1674427055/Arty/Sans_titre_-_2023-01-22T233542.827_dxjr6b.png', width:"60px" %>
              <% end %>
            </div>
            <div class="card">
              <p>Drawing</p>
              <%= link_to drawings_path do %>
                <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1674427055/Arty/Sans_titre_-_2023-01-22T233511.918_y2gxlb.png', width:"60px" %>
              <% end %>
            </div>
            <div class="card">
              <p>Digital painting</p>
              <%= link_to digital_paintings_path do %>
                <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1674427091/Arty/ablet_3_d8m2jm.png', width:"60px" %>
              <% end %>
            </div>
            <div class="card">
              <p>Photography</p>
              <%= link_to photography_path do %>
                <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1674427091/Arty/ablet_2_v1h6kf.png', width:"60px" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="right">
        <div class="profile-box">
          <div class="user-infos">
              <h3 class="user">Welcome <br><%= @user.nickname %> !</h3>
            <br>
            <p><%= current_user.email %></p>
            <p class ="city"><%= @user.city %></p>
          </div>
          <div class="user-photo">
            <% if @user.photo.attached? %>
              <%= cl_image_tag @user.photo.key , width:'100px',class:'av' %>
            <% else %>
              <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1671992140/click%20n%20pole/avatar_p2fgt6.jpg', width:'100px',class:'av' %>
            <% end %>
            <br>
            <%= link_to"Edit", edit_user_path(@user) %>
          </div>
          <hr>
        </div>
        <div class="mess-box">
          <h3>Reviews</h3>
          <br>
          <p>My 3 last reviews:</p>

          <% @reviews.last(3).each do |r| %>
          <p><small> <%=r.content.first(20)   %> </small></p>
          <% end %>
          <%= link_to"Reviews", reviews_path %>
        </div>
        <br>
      </div>

      </div>

    </div>
</div>

app/views/pages/digital_paintings.html.erb
<div class="shadow">
  <div class="container">

      <div class="digits-box gall">
        <h1>Digital paintings <span class="gtitle"> Gallery</span></h1>
        <br>
        <%= link_to "back", dashboard_path ,class:"b" %>
        <br>
        <div class="bloccc">
          <% allpaintings = Art.where(category: "digital painting") %>

          <% allpaintings.each do |art| %>

            <div class="card-gall">
              <div class="frame">
                <%= link_to art_path(art) do %>
                  <%= cl_image_tag art.photo.key, width:'300px', height:'300px'%>
                <% end %>
              </div>
              <p><b><%= art.title %></b></p>
              <small><%= art.user.email %></small>
            </div>

          <% end %>
        </div>
      </div>
    </div>

</div>

app/views/pages/drawings.html.erb
<div class="shadow">
  <div class="container">

    <div class="drawings-box gall">
      <h1>Drawings <span class="gtitle"> Gallery</span></h1>
      <br>
      <%= link_to "back", dashboard_path,class:"b"  %>
      <br>
      <div class="bloccc">
        <% allpaintings = Art.where(category: "drawing") %>
        <% allpaintings.each do |art| %>
          <div class="card-gall">
            <div class="frame">
              <%= link_to art_path(art) do %>
                <%= cl_image_tag art.photo.key, width:'300px', height:'300px'%>
              <% end %>
            </div>
            <p><b><%= art.title %></b></p>
            <small><%= art.user.email %></small>
          </div>

        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-img">
    <%= image_tag'gallery.png', width:"600px" %>
  </div>
  <div class="banner-txt">
    <h1>Arty space</h1>
    <h2>Welcome to the best digital gallery !</h2>
    <p>A simple way to share your work all around the world, and increase your visibility as an artist.</p>
    <% if current_user %>
      <%= link_to "My space", dashboard_path %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
  </div>
</div>

<div class="containerrr">

    <div class="gallerybox">
      <i class="fa-solid fa-cube"></i><h2>Get access to our galleries</h2>

      <div class="images">
        <div class="ldg-img">
          <p>Paintings</p>
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1674481369/Arty/lion_koroyj.jpg', width:"180px", height:'180px' %>
        </div>
        <div class="ldg-img">
          <p>Drawings</p>
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1674481369/Arty/bird_g7smid.jpg', width:"180px", height:'180px' %>
        </div>
        <div class="ldg-img">
          <p>Digital</p>
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1674425113/Arty/digital_pyk6m5.jpg', width:"180px", height:'180px' %>
        </div>
        <div class="ldg-img">
          <p>Photography</p>
          <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1674425110/Arty/photo_vacpzw.png', width:"180px", height:'180px' %>
        </div>
      </div>
    </div>

</div>

<div class="share-box">
  <div class="artpost">

    <div class="artext">
      <div class="words">
        <p>Create your gallery and post your art <br>
        Post your work, and get noticed !</p>
        <p>Elaborate projects with other artist</p>
      </div>
      <div class="imgtxt">
        <%= image_tag 'https://res.cloudinary.com/dhxefoe7j/image/upload/v1674493034/Arty/Sans_titre_-_2023-01-23T175648.560_fjahjr.png', width:"200px" %>
      </div>
    </div>
    <div class="t">
      <i class="fa-solid fa-cube"></i><h2>Share your work</h2>
      <% if user_signed_in? %>
        <%= link_to "Post", arts_path %>
      <% else %>
        <%= link_to "Post", new_user_session_path %>
      <% end %>
    </div>
  </div>
</div>

<footer>
    <div class="contact-info">
      <p>Contact us !</p>
      <p>
        ARTY SPACE <br>
        <small>45, Street Name <br> 14522 Planet Heaarth</small><br><br>
      </p>

      <small>All rights reserved - Copyright 2023</small>
    </div>

    <div class="social">
      <small> <%= link_to "contact@artyspace.com", "#" %> </small><br><br>
      <ul>
        <li><i class="fa-brands fa-facebook"></i></li>
        <li><i class="fa-brands fa-instagram"></i></li>
        <li><i class="fa-brands fa-youtube"></i></li>
      </ul>
    </div>
  </footer>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>

  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.select :category, Post::CATEGORIES %>
  <%= f.input :photo, as: :file %>
  <% f.input :current_user_id, input_html: {value: params[:current_user_id]} %>
  <br><br>
  <%= f.button :submit, 'Post' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dhxefoe7j/image/upload/v1674425111/Arty/A_aakh6q.png", class:'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item active">
          <% unless params[:action] == 'dashboard'%>
            <%=  link_to dashboard_path, class: "nav-link" do  %>
              <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1665345146/click%20n%20pole/home_iyuz6r.svg', width:"30px" %>
            <% end %>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to "My gallery", arts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Reviews", reviews_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
            <li class="dropdown-toggle  nav-link " id="hand" data-bs-toggle="dropdown" aria-expanded="false">
              Galleries
            </li>
              <div class="dropdown-menu  dropdown-menu-end gal" aria-labelledby="navbarDropdown ">
                <%= link_to "Painting", paintings_path, class: "nav-link droppy" %>
                <%= link_to "Drawing", drawings_path, class: "nav-link droppy" %>
                <%= link_to "Digital painting", digital_paintings_path, class: "nav-link droppy" %>
                <%= link_to "Photography", photography_path, class: "nav-link droppy" %>
              </div>
        </li>

         <li class="nav-item dropdown">
            <li class="dropdown-toggle  nav-link " id="hand" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </li>
              <div class="dropdown-menu  dropdown-menu-end" aria-labelledby="navbarDropdown ">
                <%= link_to "About", "#", class: "nav-link droppy " %>
                <%= link_to "Contact", "#", class: "nav-link droppy " %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link " %>
              </div>
        </li>





      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>